version: "3.3"

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.14-ubuntu2204
    restart: 'no'
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P4ssw0rd
      - MONGO_INITDB_DATABASE=userdb
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      vpcbr-node22-mongo7:
        ipv4_address: 10.0.70.30
  app:
    depends_on:
      - mongodb
    build: ./men-app
    restart: 'no'
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./men-app:/usr/src/webserver
    networks:
      vpcbr-node22-mongo7:
        ipv4_address: 10.0.70.40

volumes:
  db:

networks:
  vpcbr-node22-mongo7:
    driver: bridge
    ipam:
      config:
       - subnet: 10.0.70.0/24
        #  gateway: 10.0.60.1